import Head from 'next/head'
import Link from 'next/link'

import styles from '../styles/Index.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>مستخدم حالي</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`${styles.Home}`}>

          <div className={`${styles.AuthContainer} bg-blue-500 rounded-lg px-2 py-4`}>
              <div className="text-center"><span className="text-gray-100 text-xl md:text-3xl">مستخدم حالي</span></div>  
              <form action="/signup" method="post">

                  <div class="mb-4">
                    <input type="email" name="email" placeholder="البريد" required class="border outline-none border-gray-300 px-3 py-2 rounded-md w-full"/>
                  </div>

                  <div class="mb-4">
                    <input type="password" name="password" placeholder="كلمة السر" required class="border outline-none border-gray-300 px-3 py-2 rounded-md w-full"/>
                  </div>

                  <div>
                       <button class="bg-yellow-500 px-4 py-2 rounded-md">مستخدم حالي</button>
                       <Link href="/signup" class="bg-yellow-500 ml-2 px-4 py-2 rounded-md">مستخدم جديد</Link>
                  </div>
                  
              </form>

          </div>

      </div>

    </div>
  )
}